title: <p align="center"> Leonardo Meireles </p>

logo: "/images/profile_picture_round.png?raw=true"

description:
  <p align="center">
  <a href="pdf/RESUME_LEONARDO_MEIRELES.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/leo-meireles-murtha/?locale=en_US">LinkedIn</a> |
  <a href="https://github.com/leoMurtha">GitHub</a>
  </p>
  
  <p align="justify">
  ğŸ“ BSc. in Computer Science with a focus in data science - ICMC-Universidade de SÃ£o Paulo - SÃ£o Carlos.
  <br><br>
  ğŸ“š Background as a Data Scientist in a consulting firm that used big data to build products with artificial intelligence for large companies, currently working as a Data Scientist in the biggest LATAM foodtech specializing in performance marketing.
  <br><br>
  ğŸ’» As for my future, I plan to work as a Data Manager or Squad Lead in a diverse, multidisciplinary team creating new products using the potential of data analysis and machine learning.
  <br><br>
  ğŸ” In my free time, I like to produce techno music, go to concerts, practice jiu-jitsu, and do nature travel.
  <br><br>
  ğŸ’ªğŸ½ Skills/Experience - Story Telling (seaborn, matplotlib, Tableau), Machine Learning (sklearn, pycaret), Programming (Python, R, C), Data Analysis (EDAs, SQL), DevOps(Airflow, Docker, AWS).
  <br><br>
  I am currently a Data Scientist (2A - Senior) at iFood.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
